Repository morethanmin/morethan-log, pull requests merged in 2022-12, with the labels that each got.

#25 Enabling Dark Mode
  src/components/Layout/Header/index.jsx
  src/components/Theme.jsx
  src/containers/Feed/components/Tags.jsx
  src/styles/globals.css
Labels: ✨ Feature

#41 adding post author
  README.md
  morethan-log.config.js
  public/sitemap.xml
  src/containers/Feed/components/Footer.tsx
  src/containers/Feed/components/Header.tsx
  src/containers/Feed/components/SearchInput.tsx
  src/containers/Feed/components/cards/ContactCard.tsx
  src/containers/Feed/components/cards/ProfileCard.tsx
  src/containers/Feed/components/cards/ServiceCard.tsx
  src/containers/Feed/components/lists/PostList.tsx
  src/containers/Feed/components/lists/TagList.tsx
  src/containers/Feed/index.tsx
  src/containers/Post/index.tsx
  src/containers/PostDetail/components/CommentBox.tsx
  src/containers/PostDetail/components/PostFooter.tsx
  src/containers/PostDetail/components/PostHeader.tsx
  src/containers/PostDetail/index.tsx
  src/libs/notion/getAllPageIds.ts
  src/libs/notion/getAllPosts.ts
  src/libs/notion/getAllTagsFromPosts.ts
  src/libs/notion/getPageProperties.ts
  src/libs/notion/getPostBlocks.ts
  src/pages/[slug].tsx
  src/pages/index.tsx
  src/types/post.ts
  tsconfig.json
Labels: ✨ feature

#44 Adding mobile profile section, Updating README
  README.md
  morethan-log.config.js
  public/sitemap.xml
  src/components/Layout/Header/ThemeToggle.tsx
  src/components/PostCard.tsx
  src/containers/Feed/components/Footer.tsx
  src/containers/Feed/components/Header.tsx
  src/containers/Feed/components/SearchInput.tsx
  src/containers/Feed/components/cards/ContactCard.tsx
  src/containers/Feed/components/cards/MobileProfileCard.tsx
  src/containers/Feed/components/cards/ProfileCard.tsx
  src/containers/Feed/components/cards/ServiceCard.tsx
  src/containers/Feed/components/cards/index.tsx
  src/containers/Feed/components/lists/PostList.tsx
  src/containers/Feed/components/lists/TagList.tsx
  src/containers/Feed/components/lists/index.tsx
  src/containers/Feed/index.tsx
  src/containers/PostDetail/components/CommentBox.tsx
  src/containers/PostDetail/components/PostHeader.tsx
  src/containers/PostDetail/index.tsx
  src/hooks/useGtagEffect.ts
  src/hooks/useThemeEffect.ts
  src/libs/next/imageLoader.ts
  src/libs/notion/getAllPosts.ts
  src/libs/notion/getAllTagsFromPosts.ts
  src/libs/plugin/gtag.ts
  src/libs/utils/index.ts
  src/pages/[slug].tsx
  src/pages/index.tsx
  src/types/index.ts
  tsconfig.json
Labels: documentation, enhancement
