Repository morethanmin/morethan-log, pull requests merged in 2023-01, with the labels that each got.

#56 Adding Post Custom Thumbnail
  morethan-log.config.js
  public/sitemap.xml
  src/components/Layout/MetaConfig/index.tsx
  src/components/PostCard.tsx
  src/containers/Feed/components/Header.tsx
  src/containers/Feed/components/lists/PostList.tsx
  src/libs/notion/customMapImageUrl.ts
  src/libs/notion/getPageProperties.ts
  src/pages/[slug].tsx
  src/pages/index.tsx
  src/types/index.ts
Labels: ✨ feature

#63 Adding Error Page, Fixing Some Issue
  morethan-log.config.js
  next.config.js
  public/images/error.png
  src/components/PostCard.tsx
  src/containers/CustomError/index.tsx
  src/containers/Feed/components/cards/MobileProfileCard.tsx
  src/containers/Feed/components/cards/ProfileCard.tsx
  src/containers/PostDetail/components/PostHeader.tsx
  src/libs/next/imageLoader.ts
  src/libs/notion/getPageProperties.ts
  src/pages/404.tsx
  src/pages/[slug].tsx
  src/types/index.ts
Labels: bug, ✨ feature

#67 Workflow Changes + Refactoring
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/docs/CODE_OF_CONDUCT.md
  .github/docs/CONTRIBUTING.md
  .prettierrc.json
  README.md
  next-sitemap.config.js
  site.config.js
  src/components/Layout/Header/Logo.tsx
  src/components/Layout/Header/ThemeToggle.tsx
  src/components/Layout/Header/index.tsx
  src/components/Layout/MetaConfig/index.tsx
  src/components/PostCard.tsx
  src/components/Scripts.tsx
  src/components/Utterances.tsx
  src/containers/Feed/components/Footer.tsx
  src/containers/Feed/components/cards/ContactCard.tsx
  src/containers/Feed/components/cards/MobileProfileCard.tsx
  src/containers/Feed/components/cards/ProfileCard.tsx
  src/containers/Feed/components/cards/ServiceCard.tsx
  src/containers/PostDetail/components/CommentBox.tsx
  src/containers/PostDetail/components/PostHeader.tsx
  src/hooks/useGtagEffect.ts
  src/hooks/useThemeEffect.ts
  src/libs/cjk.js
  src/libs/notion/filterPublishedPosts.ts
  src/libs/notion/getAllPosts.ts
  src/libs/plugin/gtag.ts
  src/pages/404.tsx
  src/pages/[slug].tsx
  src/pages/_document.tsx
  src/pages/index.tsx
Labels: config

#71 [FIX] Adding image domain
  next.config.js
Labels: 🐛bug

#68 [Fix] notion-toggle 내부 element overflow 해결
  src/styles/notion.css
Labels: 🐛bug

#79 [REFACTOR] refactoring code
  site.config.js
  src/components/Layout/index.tsx
  src/containers/Detail/components/PageDetail/index.tsx
  src/containers/Detail/components/PostDetail/CommentBox.tsx
  src/containers/Detail/components/PostDetail/PostFooter.tsx
  src/containers/Detail/components/PostDetail/PostHeader.tsx
  src/containers/Detail/components/PostDetail/index.tsx
  src/containers/Detail/hooks/useMermaidEffect.ts
  src/containers/Detail/index.tsx
  src/libs/notion/filterPosts.ts
  src/libs/notion/filterPublishedPosts.ts
  src/libs/notion/getPosts.ts
  src/libs/notion/index.ts
  src/pages/[slug].tsx
  src/pages/index.tsx
  src/types/index.ts
Labels: enhancement

#84 [UPDATE] tailwind.config.js
  tailwind.config.js
Labels: enhancement
